OrganizationsDirectory/Controllers/PersonInOrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Context;
using DAL.Entities;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace OrganizationsDirectory.Controllers
{
    [Authorize]
    public class PersonInOrganizationsController : Controller
    {
        private readonly OrganizationsDirectoryDbContext _context;

        public PersonInOrganizationsController(OrganizationsDirectoryDbContext context)
        {
            _context = context;
        }

        // get -> PersonInOrganizations
        public IActionResult Index(string searchString, string currentFilter, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var organizationsDirectoryDbContext = _context.PersonInOrganization.Include(p => p.Organization).Include(p => p.Person).Include(p => p.Position);

            var newList = organizationsDirectoryDbContext.ToListAsync().Result;

            if (!String.IsNullOrEmpty(searchString))
            {

                newList = newList.Where(p => p.Person.FullName.ToLower().Contains(searchString.ToLower()) || p.Organization.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(newList.ToPagedList(pageNumber, pageSize));
        }

        // get -> Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personInOrganization = await _context.PersonInOrganization
                .Include(p => p.Organization)
                .Include(p => p.Person)
                .Include(p => p.Position)
                .FirstOrDefaultAsync(m => m.PersonInOrganizationId == id);
            if (personInOrganization == null)
            {
                return NotFound();
            }

            return View(personInOrganization);
        }

        // get -> Create
        public IActionResult Create()
        {
            ViewData["OrganizationId"] = new SelectList(_context.Organization, "OrganizationId", "Name");
            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "FullName");
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Position");
            return View();
        }

        // set ->  Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonInOrganizationId,OrganizationId,PersonId,PositionId")] PersonInOrganization personInOrganization)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personInOrganization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrganizationId"] = new SelectList(_context.Organization, "OrganizationId", "OrganizationId", personInOrganization.OrganizationId);
            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "PersonId", personInOrganization.PersonId);
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Position", personInOrganization.PositionId);
            return View(personInOrganization);
        }

        // get -> Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personInOrganization = await _context.PersonInOrganization.FindAsync(id);
            if (personInOrganization == null)
            {
                return NotFound();
            }
            ViewData["OrganizationId"] = new SelectList(_context.Organization, "OrganizationId", "Name", personInOrganization.OrganizationId);
            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "FullName", personInOrganization.PersonId);
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Position", personInOrganization.PositionId);
            return View(personInOrganization);
        }

        // set -> Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonInOrganizationId,OrganizationId,PersonId,PositionId")] PersonInOrganization personInOrganization)
        {
            if (id != personInOrganization.PersonInOrganizationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personInOrganization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonInOrganizationExists(personInOrganization.PersonInOrganizationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrganizationId"] = new SelectList(_context.Organization, "OrganizationId", "OrganizationId", personInOrganization.OrganizationId);
            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "PersonId", personInOrganization.PersonId);
            ViewData["PositionId"] = new SelectList(_context.Positions, "PositionId", "Position", personInOrganization.PositionId);
            return View(personInOrganization);
        }

        // get -> Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personInOrganization = await _context.PersonInOrganization
                .Include(p => p.Organization)
                .Include(p => p.Person)
                .Include(p => p.Position)
                .FirstOrDefaultAsync(m => m.PersonInOrganizationId == id);
            if (personInOrganization == null)
            {
                return NotFound();
            }

            return View(personInOrganization);
        }

        // set -> Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var personInOrganization = await _context.PersonInOrganization.FindAsync(id);
            _context.PersonInOrganization.Remove(personInOrganization);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonInOrganizationExists(int id)
        {
            return _context.PersonInOrganization.Any(e => e.PersonInOrganizationId == id);
        }
    }
}

OrganizationsDirectory/Views/PersonInOrganizations/Create.cshtml
@model DAL.Entities.PersonInOrganization

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PersonInOrganization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Organization" class="control-label"></label>
                <select asp-for="OrganizationId" class ="form-control" asp-items="ViewBag.OrganizationId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Person" class="control-label"></label>
                <select asp-for="PersonId" class ="form-control" asp-items="ViewBag.PersonId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <select asp-for="PositionId" class ="form-control" asp-items="ViewBag.PositionId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OrganizationsDirectory/Views/PersonInOrganizations/Delete.cshtml
@model DAL.Entities.PersonInOrganization

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonInOrganization</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Organization)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Organization.OrganizationId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Person)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Person.PersonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position.Position)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonInOrganizationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OrganizationsDirectory/Views/PersonInOrganizations/Details.cshtml
@model DAL.Entities.PersonInOrganization

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PersonInOrganization</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Organization)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Organization.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Person)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Person.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position.Position)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PersonInOrganizationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

OrganizationsDirectory/Views/PersonInOrganizations/Edit.cshtml
@model DAL.Entities.PersonInOrganization

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PersonInOrganization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonInOrganizationId" />
            <div class="form-group">
                <label asp-for="Organization" class="control-label"></label>
                <select asp-for="OrganizationId" class="form-control" asp-items="ViewBag.OrganizationId"></select>
                <span asp-validation-for="OrganizationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Person" class="control-label"></label>
                <select asp-for="PersonId" class="form-control" asp-items="ViewBag.PersonId"></select>
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <select asp-for="PositionId" class="form-control" asp-items="ViewBag.PositionId"></select>
                <span asp-validation-for="PositionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OrganizationsDirectory/Views/PersonInOrganizations/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<DAL.Entities.PersonInOrganization>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@using (Html.BeginForm("Index", "PersonInOrganizations", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Organization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Person)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Person.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Position)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Organization.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Person.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Position)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PersonInOrganizationId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.PersonInOrganizationId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.PersonInOrganizationId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }),
    new X.PagedList.Web.Common.PagedListRenderOptionsBase
    {
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" }
    })